### ISSUE TITLE
[Meta] Make this plugin great again 🧢 

### ISSUE THREAD

**Issue by afharo** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#966]
This plugin has a bunch of tech debt that keeps piling and blocks other work from being done. Let's try to get the ball rolling again.

- [ ] https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/958
- [ ] https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/247: In order to support many of the auto-setup features, this plugin should be a platform. This way we can connect, find the model, and expose all its features based on that.
- [ ] https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/934: Let's replace the fan and switch buttons with a proper vacuum service (when available in HomeKit and Homebridge).
- [ ] Migrate to the [MIOT spec](https://home.miot-spec.com/): supporting this spec will make it easier to integrate new models (and potentially unknown services).
- [ ] Add Xiaomi Cloud authentication: This might resolve many issues when trying to find the tokens. If users can set up their `mi.com` user and password and let the plugin figure out the tokens (maybe even refresh them automatically?).
- [ ] https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/104: It's been a long-standing request. Let's see if we can integrate with those tokens as well.

**Comment by edelmaca** [comment]
One more function I would like to see in this plugin. I got the Roborock Zeo One this year and would love to use it with the home app. Maybe someone can get the Zeo one washer/dryer to work with this plugin.

**Comment by afharo** [comment]
@edelmaca, great point! What's exactly the issue that you are facing with that model? Is it that it doesn't work with the Xiaomi app (and hence with this plugin)? A mismatch of the speeds? Or any missing features specific to that robot?

**Comment by edelmaca** [comment]
It's a Washer/Dryer combo that only works within the Roborock app. It is no robo vacuum. So maybe that plugin is not exactly the right one for this device. But it's a Roborock, so.... 🤷🏻‍♂️ 
The Machine can be started remotely but just from within the app. If I could automate it with Apple Home automations (eg. when enough solar energy is produced) that would enhance my smarthome and energy saving a lot.

**Comment by edelmaca** [comment]
Thank you. I will try the homeassistant integration of roborocks devices.

**Comment by jmswangit** [comment]
@afharo any update on the use of Roborock App tokens?

**Comment by DSimeone1989** [comment]
Hi there,
How is it going?
Are there further updates planned?
And if so, do you have a rough schedule?

Thanks a lot!

**Comment by afharo** [comment]
Hi all! I'm exploring moving this plugin to matterbridge. Given that Apple won't support Vacuums through HomeKit, it makes no sense spending my very scarce time on improving this plugin.

I'll post here and update the readme once I have a successful matterbridge plugin to share.
